/**
 * StarTest — STATE CATALOG
 *
 * The canonical list of every U.S. state + DC and the standardized test
 * each one administers. This is the source of truth for:
 *   - State pickers on landing & signup
 *   - URL slugs (e.g. /states/texas/)
 *   - State-specific page hero copy
 *   - Trust markers per state
 *   - Test calendar reminders (future)
 *   - Per-state curriculum overrides (future)
 *   - Per-state pricing experiments (future)
 *   - Per-state parent dashboards (future)
 *   - SEO metadata per state
 *
 * To add a per-state customization, edit this file.
 * To add a per-state curriculum override, also create a file at
 *   data/states/<slug>/<grade-slug>-<subject>-overrides.json
 *
 * Future fields to add (do not delete this list):
 *   - parentDashboardEnabled
 *   - schoolDistrictsSupported
 *   - localeOverride (for Spanish-primary state regions)
 *   - testFormat ('linear' | 'computer-adaptive' | 'paper')
 *   - calculatorPolicy
 *   - testDurationMinutes
 *   - retakePolicy
 *   - homeschoolEligible
 */

(function () {
  var SUBJECTS_DEFAULT = ['math'];
  var SUBJECTS_COMING_SOON_DEFAULT = ['reading', 'science', 'social-studies'];

  window.STATES = [
    {
      slug: 'alabama',
      name: 'Alabama',
      nameAbbr: 'AL',
      testName: 'ACAP',
      testFullName: 'Alabama Comprehensive Assessment Program',
      testAuthority: 'Alabama State Department of Education',
      testAuthorityShort: 'ALSDE',
      testAuthorityUrl: 'https://www.alabamaachieves.org/',
      gradesTested: ['grade-2','grade-3','grade-4','grade-5','grade-6','grade-7','grade-8'],
      testWindow: 'April',
      testWindowMonth: 4,
      description: "ACAP Summative is Alabama's annual assessment for grades 2–8. It measures progress against the Alabama Course of Study standards.",
      whatItCovers: 'Math, English Language Arts, and Science.',
      subjectsAvailable: SUBJECTS_DEFAULT,
      subjectsComingSoon: SUBJECTS_COMING_SOON_DEFAULT,
      customNotes: null,
      seoTitle: 'ACAP Test Prep for Alabama Kids — StarTest',
      seoDescription: "AI-powered ACAP practice for Alabama students. Aligned to Alabama Course of Study. Real toys for correct answers. Free during beta.",
      curriculumOverrideKey: null,
      features: {},
      pricing: null,
      active: true
    },
    {
      slug: 'alaska',
      name: 'Alaska',
      nameAbbr: 'AK',
      testName: 'AK STAR',
      testFullName: 'Alaska System of Academic Readiness',
      testAuthority: 'Alaska Department of Education',
      testAuthorityShort: 'DEED',
      testAuthorityUrl: 'https://education.alaska.gov/',
      gradesTested: ['grade-3','grade-4','grade-5','grade-6','grade-7','grade-8','grade-9'],
      testWindow: 'March–April',
      testWindowMonth: 3,
      description: "AK STAR measures student readiness in math, ELA, and science across grades 3–9 and aligns to Alaska's state academic standards.",
      whatItCovers: 'Math, English Language Arts, and Science.',
      subjectsAvailable: SUBJECTS_DEFAULT,
      subjectsComingSoon: SUBJECTS_COMING_SOON_DEFAULT,
      customNotes: null,
      seoTitle: 'AK STAR Test Prep for Alaska Kids — StarTest',
      seoDescription: "AI-powered AK STAR practice for Alaska students. Aligned to Alaska state standards. Real toys for correct answers. Free during beta.",
      curriculumOverrideKey: null,
      features: {},
      pricing: null,
      active: true
    },
    {
      slug: 'arizona',
      name: 'Arizona',
      nameAbbr: 'AZ',
      testName: 'AASA',
      testFullName: "Arizona's Academic Standards Assessment",
      testAuthority: 'Arizona Department of Education',
      testAuthorityShort: 'ADE',
      testAuthorityUrl: 'https://www.azed.gov/',
      gradesTested: ['grade-3','grade-4','grade-5','grade-6','grade-7','grade-8'],
      testWindow: 'April',
      testWindowMonth: 4,
      description: "AASA replaced AzMERIT in 2022. It tests Arizona students in grades 3–8 against the state's academic standards.",
      whatItCovers: 'Math, English Language Arts, and Science.',
      subjectsAvailable: SUBJECTS_DEFAULT,
      subjectsComingSoon: SUBJECTS_COMING_SOON_DEFAULT,
      customNotes: null,
      seoTitle: 'AASA Test Prep for Arizona Kids — StarTest',
      seoDescription: 'AI-powered AASA practice for Arizona students. Aligned to AZ state standards. Real toys for correct answers. Free during beta.',
      curriculumOverrideKey: null,
      features: {},
      pricing: null,
      active: true
    },
    {
      slug: 'arkansas',
      name: 'Arkansas',
      nameAbbr: 'AR',
      testName: 'ATLAS',
      testFullName: 'Arkansas Teaching and Learning Assessment System',
      testAuthority: 'Arkansas Department of Education',
      testAuthorityShort: 'ADE',
      testAuthorityUrl: 'https://dese.ade.arkansas.gov/',
      gradesTested: ['grade-3','grade-4','grade-5','grade-6','grade-7','grade-8','grade-9','grade-10'],
      testWindow: 'April–May',
      testWindowMonth: 4,
      description: "ATLAS replaces ACT Aspire as Arkansas's statewide assessment. It measures grade-level mastery of Arkansas state standards.",
      whatItCovers: 'Math, English Language Arts, and Science.',
      subjectsAvailable: SUBJECTS_DEFAULT,
      subjectsComingSoon: SUBJECTS_COMING_SOON_DEFAULT,
      customNotes: null,
      seoTitle: 'ATLAS Test Prep for Arkansas Kids — StarTest',
      seoDescription: 'AI-powered ATLAS practice for Arkansas students. Aligned to AR state standards. Real toys for correct answers. Free during beta.',
      curriculumOverrideKey: null,
      features: {},
      pricing: null,
      active: true
    },
    {
      slug: 'california',
      name: 'California',
      nameAbbr: 'CA',
      testName: 'CAASPP',
      testFullName: 'California Assessment of Student Performance and Progress',
      testAuthority: 'California Department of Education',
      testAuthorityShort: 'CDE',
      testAuthorityUrl: 'https://www.cde.ca.gov/',
      gradesTested: ['grade-3','grade-4','grade-5','grade-6','grade-7','grade-8','grade-11'],
      testWindow: 'March–June',
      testWindowMonth: 3,
      description: 'CAASPP includes the Smarter Balanced Assessments and is the primary measure of California student progress on state standards.',
      whatItCovers: 'Math, English Language Arts, Science, and Spanish reading/language arts.',
      subjectsAvailable: SUBJECTS_DEFAULT,
      subjectsComingSoon: SUBJECTS_COMING_SOON_DEFAULT,
      customNotes: null,
      seoTitle: 'CAASPP Test Prep for California Kids — StarTest',
      seoDescription: 'AI-powered CAASPP & Smarter Balanced practice for California students. Aligned to CA Common Core. Real toys for correct answers. Free during beta.',
      curriculumOverrideKey: null,
      features: {},
      pricing: null,
      active: true
    },
    {
      slug: 'colorado',
      name: 'Colorado',
      nameAbbr: 'CO',
      testName: 'CMAS',
      testFullName: 'Colorado Measures of Academic Success',
      testAuthority: 'Colorado Department of Education',
      testAuthorityShort: 'CDE',
      testAuthorityUrl: 'https://www.cde.state.co.us/',
      gradesTested: ['grade-3','grade-4','grade-5','grade-6','grade-7','grade-8','grade-11'],
      testWindow: 'April',
      testWindowMonth: 4,
      description: "CMAS is Colorado's annual statewide assessment in math, English, science, and social studies, aligned to the Colorado Academic Standards.",
      whatItCovers: 'Math, English Language Arts, Science, and Social Studies.',
      subjectsAvailable: SUBJECTS_DEFAULT,
      subjectsComingSoon: SUBJECTS_COMING_SOON_DEFAULT,
      customNotes: null,
      seoTitle: 'CMAS Test Prep for Colorado Kids — StarTest',
      seoDescription: 'AI-powered CMAS practice for Colorado students. Aligned to Colorado Academic Standards. Real toys for correct answers. Free during beta.',
      curriculumOverrideKey: null,
      features: {},
      pricing: null,
      active: true
    },
    {
      slug: 'connecticut',
      name: 'Connecticut',
      nameAbbr: 'CT',
      testName: 'Smarter Balanced',
      testFullName: 'Smarter Balanced Assessment',
      testAuthority: 'Connecticut State Department of Education',
      testAuthorityShort: 'CSDE',
      testAuthorityUrl: 'https://portal.ct.gov/SDE',
      gradesTested: ['grade-3','grade-4','grade-5','grade-6','grade-7','grade-8'],
      testWindow: 'March–June',
      testWindowMonth: 3,
      description: 'Connecticut uses Smarter Balanced for grades 3–8 plus the Connecticut NGSS Science Assessment.',
      whatItCovers: 'Math, English Language Arts, and Science (NGSS).',
      subjectsAvailable: SUBJECTS_DEFAULT,
      subjectsComingSoon: SUBJECTS_COMING_SOON_DEFAULT,
      customNotes: null,
      seoTitle: 'Smarter Balanced Test Prep for Connecticut Kids — StarTest',
      seoDescription: 'AI-powered Smarter Balanced practice for Connecticut students. Aligned to CT Core Standards. Real toys for correct answers. Free during beta.',
      curriculumOverrideKey: null,
      features: {},
      pricing: null,
      active: true
    },
    {
      slug: 'delaware',
      name: 'Delaware',
      nameAbbr: 'DE',
      testName: 'DeSSA',
      testFullName: 'Delaware System of Student Assessments',
      testAuthority: 'Delaware Department of Education',
      testAuthorityShort: 'DDOE',
      testAuthorityUrl: 'https://www.doe.k12.de.us/',
      gradesTested: ['grade-3','grade-4','grade-5','grade-6','grade-7','grade-8','grade-11'],
      testWindow: 'March–June',
      testWindowMonth: 3,
      description: 'DeSSA includes Smarter Balanced for math/ELA plus a Delaware NGSS-aligned science assessment.',
      whatItCovers: 'Math, English Language Arts, Science, and Social Studies.',
      subjectsAvailable: SUBJECTS_DEFAULT,
      subjectsComingSoon: SUBJECTS_COMING_SOON_DEFAULT,
      customNotes: null,
      seoTitle: 'DeSSA Test Prep for Delaware Kids — StarTest',
      seoDescription: 'AI-powered DeSSA practice for Delaware students. Aligned to DE state standards. Real toys for correct answers. Free during beta.',
      curriculumOverrideKey: null,
      features: {},
      pricing: null,
      active: true
    },
    {
      slug: 'district-of-columbia',
      name: 'District of Columbia',
      nameAbbr: 'DC',
      testName: 'DC CAPE',
      testFullName: 'District of Columbia Comprehensive Assessment Program',
      testAuthority: 'Office of the State Superintendent of Education',
      testAuthorityShort: 'OSSE',
      testAuthorityUrl: 'https://osse.dc.gov/',
      gradesTested: ['grade-3','grade-4','grade-5','grade-6','grade-7','grade-8'],
      testWindow: 'April–May',
      testWindowMonth: 4,
      description: "DC CAPE is the District of Columbia's annual assessment for grades 3–8, aligned to the Common Core State Standards.",
      whatItCovers: 'Math, English Language Arts, and Science.',
      subjectsAvailable: SUBJECTS_DEFAULT,
      subjectsComingSoon: SUBJECTS_COMING_SOON_DEFAULT,
      customNotes: null,
      seoTitle: 'DC CAPE Test Prep — StarTest',
      seoDescription: 'AI-powered DC CAPE practice for DC students. Aligned to Common Core. Real toys for correct answers. Free during beta.',
      curriculumOverrideKey: null,
      features: {},
      pricing: null,
      active: true
    },
    {
      slug: 'florida',
      name: 'Florida',
      nameAbbr: 'FL',
      testName: 'FAST',
      testFullName: 'Florida Assessment of Student Thinking',
      testAuthority: 'Florida Department of Education',
      testAuthorityShort: 'FLDOE',
      testAuthorityUrl: 'https://www.fldoe.org/',
      gradesTested: ['grade-k','grade-1','grade-2','grade-3','grade-4','grade-5','grade-6','grade-7','grade-8','grade-9','grade-10'],
      testWindow: 'Three windows: Aug–Sep, Dec, Apr–May',
      testWindowMonth: 8,
      description: 'FAST replaced the FSA in 2022. It uses three progress-monitoring windows per year instead of a single high-stakes spring test.',
      whatItCovers: 'Math and English Language Arts (Reading & Writing).',
      subjectsAvailable: SUBJECTS_DEFAULT,
      subjectsComingSoon: SUBJECTS_COMING_SOON_DEFAULT,
      customNotes: 'Florida tests three times a year — fall, winter, spring. Practicing year-round matters more here than in single-test states.',
      seoTitle: 'FAST Test Prep for Florida Kids — StarTest',
      seoDescription: 'AI-powered FAST practice for Florida students K–10. Year-round practice for all three FAST windows. Real toys for correct answers. Free during beta.',
      curriculumOverrideKey: null,
      features: { multipleWindows: true },
      pricing: null,
      active: true
    },
    {
      slug: 'georgia',
      name: 'Georgia',
      nameAbbr: 'GA',
      testName: 'Georgia Milestones',
      testFullName: 'Georgia Milestones Assessment System',
      testAuthority: 'Georgia Department of Education',
      testAuthorityShort: 'GADOE',
      testAuthorityUrl: 'https://www.gadoe.org/',
      gradesTested: ['grade-3','grade-4','grade-5','grade-6','grade-7','grade-8'],
      testWindow: 'April–May',
      testWindowMonth: 4,
      description: "Georgia Milestones is the state's annual assessment for grades 3–8 and high school, aligned to the Georgia Standards of Excellence.",
      whatItCovers: 'Math, English Language Arts, Science, and Social Studies.',
      subjectsAvailable: SUBJECTS_DEFAULT,
      subjectsComingSoon: SUBJECTS_COMING_SOON_DEFAULT,
      customNotes: null,
      seoTitle: 'Georgia Milestones Test Prep — StarTest',
      seoDescription: 'AI-powered Georgia Milestones practice for GA students. Aligned to GSE. Real toys for correct answers. Free during beta.',
      curriculumOverrideKey: null,
      features: {},
      pricing: null,
      active: true
    },
    {
      slug: 'hawaii',
      name: 'Hawaii',
      nameAbbr: 'HI',
      testName: 'Smarter Balanced',
      testFullName: 'Smarter Balanced Assessment',
      testAuthority: 'Hawaii State Department of Education',
      testAuthorityShort: 'HIDOE',
      testAuthorityUrl: 'https://www.hawaiipublicschools.org/',
      gradesTested: ['grade-3','grade-4','grade-5','grade-6','grade-7','grade-8','grade-11'],
      testWindow: 'March–May',
      testWindowMonth: 3,
      description: 'Hawaii uses Smarter Balanced for math and ELA, plus the Hawaii State Science Assessment.',
      whatItCovers: 'Math, English Language Arts, and Science.',
      subjectsAvailable: SUBJECTS_DEFAULT,
      subjectsComingSoon: SUBJECTS_COMING_SOON_DEFAULT,
      customNotes: null,
      seoTitle: 'Smarter Balanced Test Prep for Hawaii Kids — StarTest',
      seoDescription: 'AI-powered Smarter Balanced practice for Hawaii students. Aligned to HI state standards. Real toys for correct answers. Free during beta.',
      curriculumOverrideKey: null,
      features: {},
      pricing: null,
      active: true
    },
    {
      slug: 'idaho',
      name: 'Idaho',
      nameAbbr: 'ID',
      testName: 'ISAT',
      testFullName: 'Idaho Standards Achievement Test',
      testAuthority: 'Idaho State Department of Education',
      testAuthorityShort: 'SDE',
      testAuthorityUrl: 'https://www.sde.idaho.gov/',
      gradesTested: ['grade-3','grade-4','grade-5','grade-6','grade-7','grade-8','grade-10'],
      testWindow: 'April',
      testWindowMonth: 4,
      description: "ISAT uses Smarter Balanced for math/ELA plus Idaho's own science assessment, aligned to Idaho Content Standards.",
      whatItCovers: 'Math, English Language Arts, and Science.',
      subjectsAvailable: SUBJECTS_DEFAULT,
      subjectsComingSoon: SUBJECTS_COMING_SOON_DEFAULT,
      customNotes: null,
      seoTitle: 'ISAT Test Prep for Idaho Kids — StarTest',
      seoDescription: 'AI-powered ISAT practice for Idaho students. Aligned to ID state standards. Real toys for correct answers. Free during beta.',
      curriculumOverrideKey: null,
      features: {},
      pricing: null,
      active: true
    },
    {
      slug: 'illinois',
      name: 'Illinois',
      nameAbbr: 'IL',
      testName: 'IAR',
      testFullName: 'Illinois Assessment of Readiness',
      testAuthority: 'Illinois State Board of Education',
      testAuthorityShort: 'ISBE',
      testAuthorityUrl: 'https://www.isbe.net/',
      gradesTested: ['grade-3','grade-4','grade-5','grade-6','grade-7','grade-8'],
      testWindow: 'March–April',
      testWindowMonth: 3,
      description: 'IAR measures Illinois students in math and ELA in grades 3–8 against the Illinois Learning Standards.',
      whatItCovers: 'Math and English Language Arts.',
      subjectsAvailable: SUBJECTS_DEFAULT,
      subjectsComingSoon: SUBJECTS_COMING_SOON_DEFAULT,
      customNotes: null,
      seoTitle: 'IAR Test Prep for Illinois Kids — StarTest',
      seoDescription: 'AI-powered IAR practice for Illinois students. Aligned to IL Learning Standards. Real toys for correct answers. Free during beta.',
      curriculumOverrideKey: null,
      features: {},
      pricing: null,
      active: true
    },
    {
      slug: 'indiana',
      name: 'Indiana',
      nameAbbr: 'IN',
      testName: 'ILEARN',
      testFullName: 'Indiana Learning Evaluation Assessment Readiness Network',
      testAuthority: 'Indiana Department of Education',
      testAuthorityShort: 'IDOE',
      testAuthorityUrl: 'https://www.in.gov/doe/',
      gradesTested: ['grade-3','grade-4','grade-5','grade-6','grade-7','grade-8','grade-10'],
      testWindow: 'April–May',
      testWindowMonth: 4,
      description: "ILEARN is Indiana's annual assessment for grades 3–8 and high school biology.",
      whatItCovers: 'Math, English Language Arts, Science, and Social Studies.',
      subjectsAvailable: SUBJECTS_DEFAULT,
      subjectsComingSoon: SUBJECTS_COMING_SOON_DEFAULT,
      customNotes: null,
      seoTitle: 'ILEARN Test Prep for Indiana Kids — StarTest',
      seoDescription: 'AI-powered ILEARN practice for Indiana students. Aligned to IN academic standards. Real toys for correct answers. Free during beta.',
      curriculumOverrideKey: null,
      features: {},
      pricing: null,
      active: true
    },
    {
      slug: 'iowa',
      name: 'Iowa',
      nameAbbr: 'IA',
      testName: 'ISASP',
      testFullName: 'Iowa Statewide Assessment of Student Progress',
      testAuthority: 'Iowa Department of Education',
      testAuthorityShort: 'IDOE',
      testAuthorityUrl: 'https://educate.iowa.gov/',
      gradesTested: ['grade-3','grade-4','grade-5','grade-6','grade-7','grade-8','grade-10'],
      testWindow: 'March–May',
      testWindowMonth: 3,
      description: 'ISASP measures Iowa students against the Iowa Core academic standards.',
      whatItCovers: 'Math, English Language Arts, and Science.',
      subjectsAvailable: SUBJECTS_DEFAULT,
      subjectsComingSoon: SUBJECTS_COMING_SOON_DEFAULT,
      customNotes: null,
      seoTitle: 'ISASP Test Prep for Iowa Kids — StarTest',
      seoDescription: 'AI-powered ISASP practice for Iowa students. Aligned to Iowa Core. Real toys for correct answers. Free during beta.',
      curriculumOverrideKey: null,
      features: {},
      pricing: null,
      active: true
    },
    {
      slug: 'kansas',
      name: 'Kansas',
      nameAbbr: 'KS',
      testName: 'KAP',
      testFullName: 'Kansas Assessment Program',
      testAuthority: 'Kansas State Department of Education',
      testAuthorityShort: 'KSDE',
      testAuthorityUrl: 'https://www.ksde.org/',
      gradesTested: ['grade-3','grade-4','grade-5','grade-6','grade-7','grade-8','grade-10'],
      testWindow: 'March–April',
      testWindowMonth: 3,
      description: 'KAP is the Kansas Assessment Program, measuring students against Kansas Standards in English and math.',
      whatItCovers: 'Math, English Language Arts, Science, and Social Studies.',
      subjectsAvailable: SUBJECTS_DEFAULT,
      subjectsComingSoon: SUBJECTS_COMING_SOON_DEFAULT,
      customNotes: null,
      seoTitle: 'KAP Test Prep for Kansas Kids — StarTest',
      seoDescription: 'AI-powered KAP practice for Kansas students. Aligned to KS standards. Real toys for correct answers. Free during beta.',
      curriculumOverrideKey: null,
      features: {},
      pricing: null,
      active: true
    },
    {
      slug: 'kentucky',
      name: 'Kentucky',
      nameAbbr: 'KY',
      testName: 'KSA',
      testFullName: 'Kentucky Summative Assessment',
      testAuthority: 'Kentucky Department of Education',
      testAuthorityShort: 'KDE',
      testAuthorityUrl: 'https://www.education.ky.gov/',
      gradesTested: ['grade-3','grade-4','grade-5','grade-6','grade-7','grade-8','grade-10','grade-11'],
      testWindow: 'April–May',
      testWindowMonth: 4,
      description: 'KSA is the Kentucky Summative Assessment, measuring student proficiency in reading, math, science, social studies, and writing.',
      whatItCovers: 'Math, Reading, Science, Social Studies, and Writing.',
      subjectsAvailable: SUBJECTS_DEFAULT,
      subjectsComingSoon: SUBJECTS_COMING_SOON_DEFAULT,
      customNotes: null,
      seoTitle: 'KSA Test Prep for Kentucky Kids — StarTest',
      seoDescription: 'AI-powered KSA practice for Kentucky students. Aligned to KY academic standards. Real toys for correct answers. Free during beta.',
      curriculumOverrideKey: null,
      features: {},
      pricing: null,
      active: true
    },
    {
      slug: 'louisiana',
      name: 'Louisiana',
      nameAbbr: 'LA',
      testName: 'LEAP',
      testFullName: 'Louisiana Educational Assessment Program',
      testAuthority: 'Louisiana Department of Education',
      testAuthorityShort: 'LDOE',
      testAuthorityUrl: 'https://www.louisianabelieves.com/',
      gradesTested: ['grade-3','grade-4','grade-5','grade-6','grade-7','grade-8'],
      testWindow: 'April',
      testWindowMonth: 4,
      description: 'LEAP 2025 is the annual assessment of Louisiana students in grades 3–8 and high school.',
      whatItCovers: 'Math, English Language Arts, Science, and Social Studies.',
      subjectsAvailable: SUBJECTS_DEFAULT,
      subjectsComingSoon: SUBJECTS_COMING_SOON_DEFAULT,
      customNotes: null,
      seoTitle: 'LEAP Test Prep for Louisiana Kids — StarTest',
      seoDescription: 'AI-powered LEAP practice for Louisiana students. Aligned to LA student standards. Real toys for correct answers. Free during beta.',
      curriculumOverrideKey: null,
      features: {},
      pricing: null,
      active: true
    },
    {
      slug: 'maine',
      name: 'Maine',
      nameAbbr: 'ME',
      testName: 'MEA',
      testFullName: 'Maine Educational Assessment',
      testAuthority: 'Maine Department of Education',
      testAuthorityShort: 'MDOE',
      testAuthorityUrl: 'https://www.maine.gov/doe/',
      gradesTested: ['grade-3','grade-4','grade-5','grade-6','grade-7','grade-8','grade-11'],
      testWindow: 'March–May',
      testWindowMonth: 3,
      description: "MEA measures Maine student progress against the state's academic standards in math, ELA, and science.",
      whatItCovers: 'Math, English Language Arts, and Science.',
      subjectsAvailable: SUBJECTS_DEFAULT,
      subjectsComingSoon: SUBJECTS_COMING_SOON_DEFAULT,
      customNotes: null,
      seoTitle: 'MEA Test Prep for Maine Kids — StarTest',
      seoDescription: 'AI-powered MEA practice for Maine students. Aligned to ME state standards. Real toys for correct answers. Free during beta.',
      curriculumOverrideKey: null,
      features: {},
      pricing: null,
      active: true
    },
    {
      slug: 'maryland',
      name: 'Maryland',
      nameAbbr: 'MD',
      testName: 'MCAP',
      testFullName: 'Maryland Comprehensive Assessment Program',
      testAuthority: 'Maryland State Department of Education',
      testAuthorityShort: 'MSDE',
      testAuthorityUrl: 'https://marylandpublicschools.org/',
      gradesTested: ['grade-3','grade-4','grade-5','grade-6','grade-7','grade-8','grade-10'],
      testWindow: 'March–May',
      testWindowMonth: 3,
      description: "MCAP is Maryland's annual statewide assessment for grades 3–8 and high school.",
      whatItCovers: 'Math, English Language Arts, Science, and Social Studies.',
      subjectsAvailable: SUBJECTS_DEFAULT,
      subjectsComingSoon: SUBJECTS_COMING_SOON_DEFAULT,
      customNotes: null,
      seoTitle: 'MCAP Test Prep for Maryland Kids — StarTest',
      seoDescription: 'AI-powered MCAP practice for Maryland students. Aligned to MD College & Career Ready Standards. Real toys for correct answers. Free during beta.',
      curriculumOverrideKey: null,
      features: {},
      pricing: null,
      active: true
    },
    {
      slug: 'massachusetts',
      name: 'Massachusetts',
      nameAbbr: 'MA',
      testName: 'MCAS',
      testFullName: 'Massachusetts Comprehensive Assessment System',
      testAuthority: 'Massachusetts Department of Elementary and Secondary Education',
      testAuthorityShort: 'DESE',
      testAuthorityUrl: 'https://www.doe.mass.edu/',
      gradesTested: ['grade-3','grade-4','grade-5','grade-6','grade-7','grade-8','grade-10'],
      testWindow: 'March–May',
      testWindowMonth: 3,
      description: "MCAS is the Massachusetts Comprehensive Assessment System, the state's annual measure of student progress.",
      whatItCovers: 'Math, English Language Arts, Science, and Technology/Engineering.',
      subjectsAvailable: SUBJECTS_DEFAULT,
      subjectsComingSoon: SUBJECTS_COMING_SOON_DEFAULT,
      customNotes: null,
      seoTitle: 'MCAS Test Prep for Massachusetts Kids — StarTest',
      seoDescription: 'AI-powered MCAS practice for Massachusetts students. Aligned to MA Curriculum Frameworks. Real toys for correct answers. Free during beta.',
      curriculumOverrideKey: null,
      features: {},
      pricing: null,
      active: true
    },
    {
      slug: 'michigan',
      name: 'Michigan',
      nameAbbr: 'MI',
      testName: 'M-STEP',
      testFullName: 'Michigan Student Test of Educational Progress',
      testAuthority: 'Michigan Department of Education',
      testAuthorityShort: 'MDE',
      testAuthorityUrl: 'https://www.michigan.gov/mde',
      gradesTested: ['grade-3','grade-4','grade-5','grade-6','grade-7','grade-8','grade-11'],
      testWindow: 'April–May',
      testWindowMonth: 4,
      description: "M-STEP measures Michigan students against the state's academic standards in grades 3–8 and high school.",
      whatItCovers: 'Math, English Language Arts, Science, and Social Studies.',
      subjectsAvailable: SUBJECTS_DEFAULT,
      subjectsComingSoon: SUBJECTS_COMING_SOON_DEFAULT,
      customNotes: null,
      seoTitle: 'M-STEP Test Prep for Michigan Kids — StarTest',
      seoDescription: 'AI-powered M-STEP practice for Michigan students. Aligned to MI academic standards. Real toys for correct answers. Free during beta.',
      curriculumOverrideKey: null,
      features: {},
      pricing: null,
      active: true
    },
    {
      slug: 'minnesota',
      name: 'Minnesota',
      nameAbbr: 'MN',
      testName: 'MCA',
      testFullName: 'Minnesota Comprehensive Assessments',
      testAuthority: 'Minnesota Department of Education',
      testAuthorityShort: 'MDE',
      testAuthorityUrl: 'https://education.mn.gov/',
      gradesTested: ['grade-3','grade-4','grade-5','grade-6','grade-7','grade-8','grade-10','grade-11'],
      testWindow: 'March–May',
      testWindowMonth: 3,
      description: "MCA measures Minnesota students against the state's academic standards in reading, math, and science.",
      whatItCovers: 'Math, Reading, and Science.',
      subjectsAvailable: SUBJECTS_DEFAULT,
      subjectsComingSoon: SUBJECTS_COMING_SOON_DEFAULT,
      customNotes: null,
      seoTitle: 'MCA Test Prep for Minnesota Kids — StarTest',
      seoDescription: 'AI-powered MCA practice for Minnesota students. Aligned to MN academic standards. Real toys for correct answers. Free during beta.',
      curriculumOverrideKey: null,
      features: {},
      pricing: null,
      active: true
    },
    {
      slug: 'mississippi',
      name: 'Mississippi',
      nameAbbr: 'MS',
      testName: 'MAAP',
      testFullName: 'Mississippi Academic Assessment Program',
      testAuthority: 'Mississippi Department of Education',
      testAuthorityShort: 'MDE',
      testAuthorityUrl: 'https://www.mdek12.org/',
      gradesTested: ['grade-3','grade-4','grade-5','grade-6','grade-7','grade-8'],
      testWindow: 'April–May',
      testWindowMonth: 4,
      description: "MAAP is Mississippi's annual statewide assessment for grades 3–8 and high school.",
      whatItCovers: 'Math, English Language Arts, Science, and U.S. History.',
      subjectsAvailable: SUBJECTS_DEFAULT,
      subjectsComingSoon: SUBJECTS_COMING_SOON_DEFAULT,
      customNotes: null,
      seoTitle: 'MAAP Test Prep for Mississippi Kids — StarTest',
      seoDescription: 'AI-powered MAAP practice for Mississippi students. Aligned to MS College & Career-Ready Standards. Real toys for correct answers. Free during beta.',
      curriculumOverrideKey: null,
      features: {},
      pricing: null,
      active: true
    },
    {
      slug: 'missouri',
      name: 'Missouri',
      nameAbbr: 'MO',
      testName: 'MAP',
      testFullName: 'Missouri Assessment Program',
      testAuthority: 'Missouri Department of Elementary and Secondary Education',
      testAuthorityShort: 'DESE',
      testAuthorityUrl: 'https://dese.mo.gov/',
      gradesTested: ['grade-3','grade-4','grade-5','grade-6','grade-7','grade-8'],
      testWindow: 'March–May',
      testWindowMonth: 3,
      description: 'MAP is the Missouri Assessment Program, measuring students against Missouri Learning Standards.',
      whatItCovers: 'Math, English Language Arts, and Science.',
      subjectsAvailable: SUBJECTS_DEFAULT,
      subjectsComingSoon: SUBJECTS_COMING_SOON_DEFAULT,
      customNotes: null,
      seoTitle: 'MAP Test Prep for Missouri Kids — StarTest',
      seoDescription: 'AI-powered MAP practice for Missouri students. Aligned to MO Learning Standards. Real toys for correct answers. Free during beta.',
      curriculumOverrideKey: null,
      features: {},
      pricing: null,
      active: true
    },
    {
      slug: 'montana',
      name: 'Montana',
      nameAbbr: 'MT',
      testName: 'Smarter Balanced',
      testFullName: 'Smarter Balanced Assessment',
      testAuthority: 'Montana Office of Public Instruction',
      testAuthorityShort: 'OPI',
      testAuthorityUrl: 'https://opi.mt.gov/',
      gradesTested: ['grade-3','grade-4','grade-5','grade-6','grade-7','grade-8','grade-11'],
      testWindow: 'March–June',
      testWindowMonth: 3,
      description: 'Montana uses Smarter Balanced for math/ELA plus the Montana Science Assessment.',
      whatItCovers: 'Math, English Language Arts, and Science.',
      subjectsAvailable: SUBJECTS_DEFAULT,
      subjectsComingSoon: SUBJECTS_COMING_SOON_DEFAULT,
      customNotes: null,
      seoTitle: 'Smarter Balanced Test Prep for Montana Kids — StarTest',
      seoDescription: 'AI-powered Smarter Balanced practice for Montana students. Aligned to MT Content Standards. Real toys for correct answers. Free during beta.',
      curriculumOverrideKey: null,
      features: {},
      pricing: null,
      active: true
    },
    {
      slug: 'nebraska',
      name: 'Nebraska',
      nameAbbr: 'NE',
      testName: 'NSCAS',
      testFullName: 'Nebraska Student-Centered Assessment System',
      testAuthority: 'Nebraska Department of Education',
      testAuthorityShort: 'NDE',
      testAuthorityUrl: 'https://www.education.ne.gov/',
      gradesTested: ['grade-3','grade-4','grade-5','grade-6','grade-7','grade-8','grade-11'],
      testWindow: 'March–April',
      testWindowMonth: 3,
      description: 'NSCAS is the Nebraska Student-Centered Assessment System, measuring student progress against Nebraska College & Career Ready Standards.',
      whatItCovers: 'Math, English Language Arts, and Science.',
      subjectsAvailable: SUBJECTS_DEFAULT,
      subjectsComingSoon: SUBJECTS_COMING_SOON_DEFAULT,
      customNotes: null,
      seoTitle: 'NSCAS Test Prep for Nebraska Kids — StarTest',
      seoDescription: 'AI-powered NSCAS practice for Nebraska students. Aligned to NE College & Career Ready Standards. Real toys for correct answers. Free during beta.',
      curriculumOverrideKey: null,
      features: {},
      pricing: null,
      active: true
    },
    {
      slug: 'nevada',
      name: 'Nevada',
      nameAbbr: 'NV',
      testName: 'Smarter Balanced',
      testFullName: 'Smarter Balanced Assessment',
      testAuthority: 'Nevada Department of Education',
      testAuthorityShort: 'NDE',
      testAuthorityUrl: 'https://doe.nv.gov/',
      gradesTested: ['grade-3','grade-4','grade-5','grade-6','grade-7','grade-8','grade-11'],
      testWindow: 'March–May',
      testWindowMonth: 3,
      description: 'Nevada uses Smarter Balanced for math/ELA plus the Nevada Science Assessment.',
      whatItCovers: 'Math, English Language Arts, and Science.',
      subjectsAvailable: SUBJECTS_DEFAULT,
      subjectsComingSoon: SUBJECTS_COMING_SOON_DEFAULT,
      customNotes: null,
      seoTitle: 'Smarter Balanced Test Prep for Nevada Kids — StarTest',
      seoDescription: 'AI-powered Smarter Balanced practice for Nevada students. Aligned to NV Academic Content Standards. Real toys for correct answers. Free during beta.',
      curriculumOverrideKey: null,
      features: {},
      pricing: null,
      active: true
    },
    {
      slug: 'new-hampshire',
      name: 'New Hampshire',
      nameAbbr: 'NH',
      testName: 'NH SAS',
      testFullName: 'New Hampshire Statewide Assessment System',
      testAuthority: 'New Hampshire Department of Education',
      testAuthorityShort: 'NHDOE',
      testAuthorityUrl: 'https://www.education.nh.gov/',
      gradesTested: ['grade-3','grade-4','grade-5','grade-6','grade-7','grade-8','grade-11'],
      testWindow: 'March–May',
      testWindowMonth: 3,
      description: 'NH SAS measures New Hampshire student progress in math, ELA, and science using a competency-based approach.',
      whatItCovers: 'Math, English Language Arts, and Science.',
      subjectsAvailable: SUBJECTS_DEFAULT,
      subjectsComingSoon: SUBJECTS_COMING_SOON_DEFAULT,
      customNotes: null,
      seoTitle: 'NH SAS Test Prep for New Hampshire Kids — StarTest',
      seoDescription: 'AI-powered NH SAS practice for New Hampshire students. Aligned to NH state standards. Real toys for correct answers. Free during beta.',
      curriculumOverrideKey: null,
      features: {},
      pricing: null,
      active: true
    },
    {
      slug: 'new-jersey',
      name: 'New Jersey',
      nameAbbr: 'NJ',
      testName: 'NJSLA',
      testFullName: 'New Jersey Student Learning Assessments',
      testAuthority: 'New Jersey Department of Education',
      testAuthorityShort: 'NJDOE',
      testAuthorityUrl: 'https://www.nj.gov/education/',
      gradesTested: ['grade-3','grade-4','grade-5','grade-6','grade-7','grade-8','grade-11'],
      testWindow: 'April–May',
      testWindowMonth: 4,
      description: 'NJSLA is the New Jersey Student Learning Assessments, measuring students against the New Jersey Student Learning Standards.',
      whatItCovers: 'Math, English Language Arts, and Science.',
      subjectsAvailable: SUBJECTS_DEFAULT,
      subjectsComingSoon: SUBJECTS_COMING_SOON_DEFAULT,
      customNotes: null,
      seoTitle: 'NJSLA Test Prep for New Jersey Kids — StarTest',
      seoDescription: 'AI-powered NJSLA practice for New Jersey students. Aligned to NJ Student Learning Standards. Real toys for correct answers. Free during beta.',
      curriculumOverrideKey: null,
      features: {},
      pricing: null,
      active: true
    },
    {
      slug: 'new-mexico',
      name: 'New Mexico',
      nameAbbr: 'NM',
      testName: 'NM-MSSA',
      testFullName: 'New Mexico Measures of Student Success and Achievement',
      testAuthority: 'New Mexico Public Education Department',
      testAuthorityShort: 'NMPED',
      testAuthorityUrl: 'https://webnew.ped.state.nm.us/',
      gradesTested: ['grade-3','grade-4','grade-5','grade-6','grade-7','grade-8'],
      testWindow: 'April–May',
      testWindowMonth: 4,
      description: "NM-MSSA is New Mexico's annual assessment for grades 3–8, measuring student progress against state standards.",
      whatItCovers: 'Math, English Language Arts, and Science.',
      subjectsAvailable: SUBJECTS_DEFAULT,
      subjectsComingSoon: SUBJECTS_COMING_SOON_DEFAULT,
      customNotes: null,
      seoTitle: 'NM-MSSA Test Prep for New Mexico Kids — StarTest',
      seoDescription: 'AI-powered NM-MSSA practice for New Mexico students. Aligned to NM standards. Real toys for correct answers. Free during beta.',
      curriculumOverrideKey: null,
      features: {},
      pricing: null,
      active: true
    },
    {
      slug: 'new-york',
      name: 'New York',
      nameAbbr: 'NY',
      testName: 'NY State Tests',
      testFullName: 'New York State Testing Program',
      testAuthority: 'New York State Education Department',
      testAuthorityShort: 'NYSED',
      testAuthorityUrl: 'https://www.nysed.gov/',
      gradesTested: ['grade-3','grade-4','grade-5','grade-6','grade-7','grade-8'],
      testWindow: 'April–May',
      testWindowMonth: 4,
      description: 'New York State Tests measure students in grades 3–8 against the Next Generation Learning Standards.',
      whatItCovers: 'Math, English Language Arts, Science, and Social Studies.',
      subjectsAvailable: SUBJECTS_DEFAULT,
      subjectsComingSoon: SUBJECTS_COMING_SOON_DEFAULT,
      customNotes: null,
      seoTitle: 'NY State Test Prep for New York Kids — StarTest',
      seoDescription: 'AI-powered NY State Test practice for New York students. Aligned to Next Generation Learning Standards. Real toys for correct answers. Free during beta.',
      curriculumOverrideKey: null,
      features: {},
      pricing: null,
      active: true
    },
    {
      slug: 'north-carolina',
      name: 'North Carolina',
      nameAbbr: 'NC',
      testName: 'EOG',
      testFullName: 'North Carolina End-of-Grade Tests',
      testAuthority: 'North Carolina Department of Public Instruction',
      testAuthorityShort: 'NCDPI',
      testAuthorityUrl: 'https://www.dpi.nc.gov/',
      gradesTested: ['grade-3','grade-4','grade-5','grade-6','grade-7','grade-8'],
      testWindow: 'May–June',
      testWindowMonth: 5,
      description: "EOG tests are North Carolina's End-of-Grade tests for students in grades 3–8.",
      whatItCovers: 'Math, English Language Arts, and Science (grades 5 & 8).',
      subjectsAvailable: SUBJECTS_DEFAULT,
      subjectsComingSoon: SUBJECTS_COMING_SOON_DEFAULT,
      customNotes: null,
      seoTitle: 'EOG Test Prep for North Carolina Kids — StarTest',
      seoDescription: 'AI-powered EOG practice for North Carolina students. Aligned to NC Standard Course of Study. Real toys for correct answers. Free during beta.',
      curriculumOverrideKey: null,
      features: {},
      pricing: null,
      active: true
    },
    {
      slug: 'north-dakota',
      name: 'North Dakota',
      nameAbbr: 'ND',
      testName: 'NDSA',
      testFullName: 'North Dakota State Assessment',
      testAuthority: 'North Dakota Department of Public Instruction',
      testAuthorityShort: 'NDDPI',
      testAuthorityUrl: 'https://www.nd.gov/dpi/',
      gradesTested: ['grade-3','grade-4','grade-5','grade-6','grade-7','grade-8','grade-10'],
      testWindow: 'March–May',
      testWindowMonth: 3,
      description: "NDSA is North Dakota's State Assessment, measuring students against ND Content Standards.",
      whatItCovers: 'Math, English Language Arts, and Science.',
      subjectsAvailable: SUBJECTS_DEFAULT,
      subjectsComingSoon: SUBJECTS_COMING_SOON_DEFAULT,
      customNotes: null,
      seoTitle: 'NDSA Test Prep for North Dakota Kids — StarTest',
      seoDescription: 'AI-powered NDSA practice for North Dakota students. Aligned to ND Content Standards. Real toys for correct answers. Free during beta.',
      curriculumOverrideKey: null,
      features: {},
      pricing: null,
      active: true
    },
    {
      slug: 'ohio',
      name: 'Ohio',
      nameAbbr: 'OH',
      testName: 'Ohio State Tests',
      testFullName: "Ohio's State Tests",
      testAuthority: 'Ohio Department of Education',
      testAuthorityShort: 'ODE',
      testAuthorityUrl: 'https://education.ohio.gov/',
      gradesTested: ['grade-3','grade-4','grade-5','grade-6','grade-7','grade-8'],
      testWindow: 'April–May',
      testWindowMonth: 4,
      description: "Ohio's State Tests measure students against Ohio's Learning Standards in grades 3–8 and high school.",
      whatItCovers: 'Math, English Language Arts, Science, and Social Studies.',
      subjectsAvailable: SUBJECTS_DEFAULT,
      subjectsComingSoon: SUBJECTS_COMING_SOON_DEFAULT,
      customNotes: null,
      seoTitle: 'Ohio State Test Prep — StarTest',
      seoDescription: "AI-powered Ohio State Test practice. Aligned to Ohio's Learning Standards. Real toys for correct answers. Free during beta.",
      curriculumOverrideKey: null,
      features: {},
      pricing: null,
      active: true
    },
    {
      slug: 'oklahoma',
      name: 'Oklahoma',
      nameAbbr: 'OK',
      testName: 'OSTP',
      testFullName: 'Oklahoma School Testing Program',
      testAuthority: 'Oklahoma State Department of Education',
      testAuthorityShort: 'OSDE',
      testAuthorityUrl: 'https://sde.ok.gov/',
      gradesTested: ['grade-3','grade-4','grade-5','grade-6','grade-7','grade-8'],
      testWindow: 'April',
      testWindowMonth: 4,
      description: 'OSTP is the Oklahoma School Testing Program, measuring students against Oklahoma Academic Standards.',
      whatItCovers: 'Math, English Language Arts, Science, and U.S. History.',
      subjectsAvailable: SUBJECTS_DEFAULT,
      subjectsComingSoon: SUBJECTS_COMING_SOON_DEFAULT,
      customNotes: null,
      seoTitle: 'OSTP Test Prep for Oklahoma Kids — StarTest',
      seoDescription: 'AI-powered OSTP practice for Oklahoma students. Aligned to OK Academic Standards. Real toys for correct answers. Free during beta.',
      curriculumOverrideKey: null,
      features: {},
      pricing: null,
      active: true
    },
    {
      slug: 'oregon',
      name: 'Oregon',
      nameAbbr: 'OR',
      testName: 'OSAS',
      testFullName: 'Oregon Statewide Assessment System',
      testAuthority: 'Oregon Department of Education',
      testAuthorityShort: 'ODE',
      testAuthorityUrl: 'https://www.oregon.gov/ode/',
      gradesTested: ['grade-3','grade-4','grade-5','grade-6','grade-7','grade-8','grade-11'],
      testWindow: 'March–June',
      testWindowMonth: 3,
      description: 'OSAS uses Smarter Balanced for math/ELA plus the Oregon Science Assessment.',
      whatItCovers: 'Math, English Language Arts, and Science.',
      subjectsAvailable: SUBJECTS_DEFAULT,
      subjectsComingSoon: SUBJECTS_COMING_SOON_DEFAULT,
      customNotes: null,
      seoTitle: 'OSAS Test Prep for Oregon Kids — StarTest',
      seoDescription: 'AI-powered OSAS practice for Oregon students. Aligned to Oregon state standards. Real toys for correct answers. Free during beta.',
      curriculumOverrideKey: null,
      features: {},
      pricing: null,
      active: true
    },
    {
      slug: 'pennsylvania',
      name: 'Pennsylvania',
      nameAbbr: 'PA',
      testName: 'PSSA',
      testFullName: 'Pennsylvania System of School Assessment',
      testAuthority: 'Pennsylvania Department of Education',
      testAuthorityShort: 'PDE',
      testAuthorityUrl: 'https://www.education.pa.gov/',
      gradesTested: ['grade-3','grade-4','grade-5','grade-6','grade-7','grade-8'],
      testWindow: 'April',
      testWindowMonth: 4,
      description: 'PSSA is the Pennsylvania System of School Assessment, measuring students against PA Core Standards.',
      whatItCovers: 'Math, English Language Arts, and Science (grades 4 & 8).',
      subjectsAvailable: SUBJECTS_DEFAULT,
      subjectsComingSoon: SUBJECTS_COMING_SOON_DEFAULT,
      customNotes: null,
      seoTitle: 'PSSA Test Prep for Pennsylvania Kids — StarTest',
      seoDescription: 'AI-powered PSSA practice for Pennsylvania students. Aligned to PA Core Standards. Real toys for correct answers. Free during beta.',
      curriculumOverrideKey: null,
      features: {},
      pricing: null,
      active: true
    },
    {
      slug: 'rhode-island',
      name: 'Rhode Island',
      nameAbbr: 'RI',
      testName: 'RICAS',
      testFullName: 'Rhode Island Comprehensive Assessment System',
      testAuthority: 'Rhode Island Department of Education',
      testAuthorityShort: 'RIDE',
      testAuthorityUrl: 'https://www.ride.ri.gov/',
      gradesTested: ['grade-3','grade-4','grade-5','grade-6','grade-7','grade-8','grade-10'],
      testWindow: 'March–May',
      testWindowMonth: 3,
      description: "RICAS is Rhode Island's Comprehensive Assessment System, modeled on Massachusetts' MCAS.",
      whatItCovers: 'Math and English Language Arts.',
      subjectsAvailable: SUBJECTS_DEFAULT,
      subjectsComingSoon: SUBJECTS_COMING_SOON_DEFAULT,
      customNotes: null,
      seoTitle: 'RICAS Test Prep for Rhode Island Kids — StarTest',
      seoDescription: 'AI-powered RICAS practice for Rhode Island students. Aligned to RI standards. Real toys for correct answers. Free during beta.',
      curriculumOverrideKey: null,
      features: {},
      pricing: null,
      active: true
    },
    {
      slug: 'south-carolina',
      name: 'South Carolina',
      nameAbbr: 'SC',
      testName: 'SC READY',
      testFullName: 'South Carolina Palmetto Assessment of State Standards',
      testAuthority: 'South Carolina Department of Education',
      testAuthorityShort: 'SCDE',
      testAuthorityUrl: 'https://ed.sc.gov/',
      gradesTested: ['grade-3','grade-4','grade-5','grade-6','grade-7','grade-8'],
      testWindow: 'May',
      testWindowMonth: 5,
      description: 'SC READY measures South Carolina students against state standards in math and English Language Arts.',
      whatItCovers: 'Math, English Language Arts, and Science (SCPASS).',
      subjectsAvailable: SUBJECTS_DEFAULT,
      subjectsComingSoon: SUBJECTS_COMING_SOON_DEFAULT,
      customNotes: null,
      seoTitle: 'SC READY Test Prep for South Carolina Kids — StarTest',
      seoDescription: 'AI-powered SC READY practice for South Carolina students. Aligned to SC College and Career Ready Standards. Real toys for correct answers. Free during beta.',
      curriculumOverrideKey: null,
      features: {},
      pricing: null,
      active: true
    },
    {
      slug: 'south-dakota',
      name: 'South Dakota',
      nameAbbr: 'SD',
      testName: 'SD-CRT',
      testFullName: 'South Dakota Criterion-Referenced Test',
      testAuthority: 'South Dakota Department of Education',
      testAuthorityShort: 'SDDOE',
      testAuthorityUrl: 'https://doe.sd.gov/',
      gradesTested: ['grade-3','grade-4','grade-5','grade-6','grade-7','grade-8','grade-11'],
      testWindow: 'March–May',
      testWindowMonth: 3,
      description: 'South Dakota uses Smarter Balanced for math/ELA plus the South Dakota Science Assessment.',
      whatItCovers: 'Math, English Language Arts, and Science.',
      subjectsAvailable: SUBJECTS_DEFAULT,
      subjectsComingSoon: SUBJECTS_COMING_SOON_DEFAULT,
      customNotes: null,
      seoTitle: 'South Dakota State Test Prep — StarTest',
      seoDescription: 'AI-powered South Dakota state test practice. Aligned to SD Content Standards. Real toys for correct answers. Free during beta.',
      curriculumOverrideKey: null,
      features: {},
      pricing: null,
      active: true
    },
    {
      slug: 'tennessee',
      name: 'Tennessee',
      nameAbbr: 'TN',
      testName: 'TCAP',
      testFullName: 'Tennessee Comprehensive Assessment Program',
      testAuthority: 'Tennessee Department of Education',
      testAuthorityShort: 'TDOE',
      testAuthorityUrl: 'https://www.tn.gov/education',
      gradesTested: ['grade-3','grade-4','grade-5','grade-6','grade-7','grade-8'],
      testWindow: 'April–May',
      testWindowMonth: 4,
      description: 'TCAP is the Tennessee Comprehensive Assessment Program, measuring students against the Tennessee Academic Standards.',
      whatItCovers: 'Math, English Language Arts, Science, and Social Studies.',
      subjectsAvailable: SUBJECTS_DEFAULT,
      subjectsComingSoon: SUBJECTS_COMING_SOON_DEFAULT,
      customNotes: null,
      seoTitle: 'TCAP Test Prep for Tennessee Kids — StarTest',
      seoDescription: 'AI-powered TCAP practice for Tennessee students. Aligned to TN Academic Standards. Real toys for correct answers. Free during beta.',
      curriculumOverrideKey: null,
      features: {},
      pricing: null,
      active: true
    },
    {
      slug: 'texas',
      name: 'Texas',
      nameAbbr: 'TX',
      testName: 'STAAR',
      testFullName: 'State of Texas Assessments of Academic Readiness',
      testAuthority: 'Texas Education Agency',
      testAuthorityShort: 'TEA',
      testAuthorityUrl: 'https://tea.texas.gov/',
      gradesTested: ['grade-3','grade-4','grade-5','grade-6','grade-7','grade-8','algebra-1'],
      testWindow: 'April–May',
      testWindowMonth: 4,
      description: 'STAAR is the Texas state test for grades 3–8 plus high school End-of-Course exams. It measures progress against the Texas Essential Knowledge and Skills (TEKS).',
      whatItCovers: 'Math, Reading Language Arts, Science, Social Studies.',
      subjectsAvailable: SUBJECTS_DEFAULT,
      subjectsComingSoon: SUBJECTS_COMING_SOON_DEFAULT,
      customNotes: 'Texas is our home state — the deepest content alignment ships here first.',
      seoTitle: 'STAAR Test Prep for Texas Kids — StarTest',
      seoDescription: 'AI-powered STAAR practice for Texas students grades 3–8 and Algebra 1. Aligned to TEKS standards. Real toys for correct answers. Free during beta.',
      curriculumOverrideKey: 'tx',
      features: { homeState: true },
      pricing: null,
      active: true
    },
    {
      slug: 'utah',
      name: 'Utah',
      nameAbbr: 'UT',
      testName: 'RISE',
      testFullName: 'Readiness Improvement Success Empowerment',
      testAuthority: 'Utah State Board of Education',
      testAuthorityShort: 'USBE',
      testAuthorityUrl: 'https://www.schools.utah.gov/',
      gradesTested: ['grade-3','grade-4','grade-5','grade-6','grade-7','grade-8'],
      testWindow: 'March–May',
      testWindowMonth: 3,
      description: 'RISE is the Utah state test for students in grades 3–8, measuring progress against Utah Core Standards.',
      whatItCovers: 'Math, English Language Arts, and Science.',
      subjectsAvailable: SUBJECTS_DEFAULT,
      subjectsComingSoon: SUBJECTS_COMING_SOON_DEFAULT,
      customNotes: null,
      seoTitle: 'RISE Test Prep for Utah Kids — StarTest',
      seoDescription: 'AI-powered RISE practice for Utah students. Aligned to Utah Core Standards. Real toys for correct answers. Free during beta.',
      curriculumOverrideKey: null,
      features: {},
      pricing: null,
      active: true
    },
    {
      slug: 'vermont',
      name: 'Vermont',
      nameAbbr: 'VT',
      testName: 'Smarter Balanced',
      testFullName: 'Smarter Balanced Assessment',
      testAuthority: 'Vermont Agency of Education',
      testAuthorityShort: 'AOE',
      testAuthorityUrl: 'https://education.vermont.gov/',
      gradesTested: ['grade-3','grade-4','grade-5','grade-6','grade-7','grade-8','grade-11'],
      testWindow: 'March–May',
      testWindowMonth: 3,
      description: 'Vermont uses Smarter Balanced for math/ELA plus the Vermont Science Assessment.',
      whatItCovers: 'Math, English Language Arts, and Science.',
      subjectsAvailable: SUBJECTS_DEFAULT,
      subjectsComingSoon: SUBJECTS_COMING_SOON_DEFAULT,
      customNotes: null,
      seoTitle: 'Smarter Balanced Test Prep for Vermont Kids — StarTest',
      seoDescription: 'AI-powered Smarter Balanced practice for Vermont students. Aligned to VT state standards. Real toys for correct answers. Free during beta.',
      curriculumOverrideKey: null,
      features: {},
      pricing: null,
      active: true
    },
    {
      slug: 'virginia',
      name: 'Virginia',
      nameAbbr: 'VA',
      testName: 'SOL',
      testFullName: 'Standards of Learning Assessments',
      testAuthority: 'Virginia Department of Education',
      testAuthorityShort: 'VDOE',
      testAuthorityUrl: 'https://www.doe.virginia.gov/',
      gradesTested: ['grade-3','grade-4','grade-5','grade-6','grade-7','grade-8'],
      testWindow: 'April–May',
      testWindowMonth: 4,
      description: 'SOL Assessments measure Virginia student progress against the Virginia Standards of Learning.',
      whatItCovers: 'Math, English Language Arts, Science, Social Studies.',
      subjectsAvailable: SUBJECTS_DEFAULT,
      subjectsComingSoon: SUBJECTS_COMING_SOON_DEFAULT,
      customNotes: null,
      seoTitle: 'SOL Test Prep for Virginia Kids — StarTest',
      seoDescription: 'AI-powered SOL practice for Virginia students. Aligned to VA Standards of Learning. Real toys for correct answers. Free during beta.',
      curriculumOverrideKey: null,
      features: {},
      pricing: null,
      active: true
    },
    {
      slug: 'washington',
      name: 'Washington',
      nameAbbr: 'WA',
      testName: 'Smarter Balanced',
      testFullName: 'Smarter Balanced Assessment',
      testAuthority: 'Office of Superintendent of Public Instruction',
      testAuthorityShort: 'OSPI',
      testAuthorityUrl: 'https://www.k12.wa.us/',
      gradesTested: ['grade-3','grade-4','grade-5','grade-6','grade-7','grade-8','grade-11'],
      testWindow: 'March–June',
      testWindowMonth: 3,
      description: 'Washington uses Smarter Balanced for math/ELA plus the Washington Comprehensive Assessment of Science.',
      whatItCovers: 'Math, English Language Arts, and Science.',
      subjectsAvailable: SUBJECTS_DEFAULT,
      subjectsComingSoon: SUBJECTS_COMING_SOON_DEFAULT,
      customNotes: null,
      seoTitle: 'Smarter Balanced Test Prep for Washington Kids — StarTest',
      seoDescription: 'AI-powered Smarter Balanced practice for Washington students. Aligned to WA Learning Standards. Real toys for correct answers. Free during beta.',
      curriculumOverrideKey: null,
      features: {},
      pricing: null,
      active: true
    },
    {
      slug: 'west-virginia',
      name: 'West Virginia',
      nameAbbr: 'WV',
      testName: 'WVGSA',
      testFullName: 'West Virginia General Summative Assessment',
      testAuthority: 'West Virginia Department of Education',
      testAuthorityShort: 'WVDE',
      testAuthorityUrl: 'https://wvde.us/',
      gradesTested: ['grade-3','grade-4','grade-5','grade-6','grade-7','grade-8','grade-11'],
      testWindow: 'March–May',
      testWindowMonth: 3,
      description: 'WVGSA measures West Virginia student progress against state College & Career Ready Standards.',
      whatItCovers: 'Math, English Language Arts, and Science.',
      subjectsAvailable: SUBJECTS_DEFAULT,
      subjectsComingSoon: SUBJECTS_COMING_SOON_DEFAULT,
      customNotes: null,
      seoTitle: 'WVGSA Test Prep for West Virginia Kids — StarTest',
      seoDescription: 'AI-powered WVGSA practice for West Virginia students. Aligned to WV CCR Standards. Real toys for correct answers. Free during beta.',
      curriculumOverrideKey: null,
      features: {},
      pricing: null,
      active: true
    },
    {
      slug: 'wisconsin',
      name: 'Wisconsin',
      nameAbbr: 'WI',
      testName: 'Forward Exam',
      testFullName: 'Wisconsin Forward Exam',
      testAuthority: 'Wisconsin Department of Public Instruction',
      testAuthorityShort: 'DPI',
      testAuthorityUrl: 'https://dpi.wi.gov/',
      gradesTested: ['grade-3','grade-4','grade-5','grade-6','grade-7','grade-8','grade-10'],
      testWindow: 'March–May',
      testWindowMonth: 3,
      description: 'The Wisconsin Forward Exam measures students against Wisconsin Academic Standards.',
      whatItCovers: 'Math, English Language Arts, Science, and Social Studies.',
      subjectsAvailable: SUBJECTS_DEFAULT,
      subjectsComingSoon: SUBJECTS_COMING_SOON_DEFAULT,
      customNotes: null,
      seoTitle: 'Wisconsin Forward Exam Prep — StarTest',
      seoDescription: 'AI-powered Forward Exam practice for Wisconsin students. Aligned to WI Academic Standards. Real toys for correct answers. Free during beta.',
      curriculumOverrideKey: null,
      features: {},
      pricing: null,
      active: true
    },
    {
      slug: 'wyoming',
      name: 'Wyoming',
      nameAbbr: 'WY',
      testName: 'WY-TOPP',
      testFullName: 'Wyoming Test of Proficiency and Progress',
      testAuthority: 'Wyoming Department of Education',
      testAuthorityShort: 'WDE',
      testAuthorityUrl: 'https://edu.wyoming.gov/',
      gradesTested: ['grade-3','grade-4','grade-5','grade-6','grade-7','grade-8'],
      testWindow: 'March–May',
      testWindowMonth: 3,
      description: 'WY-TOPP is the Wyoming Test of Proficiency and Progress, measuring students against Wyoming Content and Performance Standards.',
      whatItCovers: 'Math, English Language Arts, and Science.',
      subjectsAvailable: SUBJECTS_DEFAULT,
      subjectsComingSoon: SUBJECTS_COMING_SOON_DEFAULT,
      customNotes: null,
      seoTitle: 'WY-TOPP Test Prep for Wyoming Kids — StarTest',
      seoDescription: 'AI-powered WY-TOPP practice for Wyoming students. Aligned to WY standards. Real toys for correct answers. Free during beta.',
      curriculumOverrideKey: null,
      features: {},
      pricing: null,
      active: true
    }
  ];

  // ============================================================
  // STATE LOOKUP HELPERS — Available globally as window.STATES_API
  // ============================================================
  window.STATES_API = {
    /** Get state by slug. Returns null if not found. */
    getBySlug: function (slug) {
      return window.STATES.find(function (s) { return s.slug === slug; }) || null;
    },
    /** Get state by 2-letter abbreviation (e.g., 'TX'). Returns null if not found. */
    getByAbbr: function (abbr) {
      var upper = String(abbr || '').toUpperCase();
      return window.STATES.find(function (s) { return s.nameAbbr === upper; }) || null;
    },
    /** Get state by full name (case-insensitive). Returns null if not found. */
    getByName: function (name) {
      var lower = String(name || '').toLowerCase();
      return window.STATES.find(function (s) { return s.name.toLowerCase() === lower; }) || null;
    },
    /** Get all active states (currently shipping content). */
    getActive: function () {
      return window.STATES.filter(function (s) { return s.active; });
    },
    /** Get states alphabetically. */
    getAlphabetical: function () {
      return window.STATES.slice().sort(function (a, b) { return a.name.localeCompare(b.name); });
    },
    /** Get the home state (Texas, currently). */
    getHomeState: function () {
      return window.STATES.find(function (s) { return s.features && s.features.homeState; }) || null;
    },
    /** Check if a grade is offered in a given state. */
    isGradeInState: function (stateSlug, gradeSlug) {
      var state = this.getBySlug(stateSlug);
      return state ? state.gradesTested.indexOf(gradeSlug) !== -1 : false;
    },
    /** Check if a subject is available in a given state. */
    isSubjectAvailable: function (stateSlug, subject) {
      var state = this.getBySlug(stateSlug);
      return state ? state.subjectsAvailable.indexOf(subject) !== -1 : false;
    },
    /** Total count for marketing copy ("Practice for all 51 state tests"). */
    totalCount: function () {
      return window.STATES.length;
    },
    /** Active count for marketing copy. */
    activeCount: function () {
      return window.STATES.filter(function (s) { return s.active; }).length;
    }
  };
})();
